"""Add mood field to Drawing

Revision ID: 6a25ad302838
Revises: 6b5f22790a9c
Create Date: 2025-05-31 14:35:57.419022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a25ad302838'
down_revision = '6b5f22790a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
